"/home/moebius/reactos/boot/bootdata/bootcdregtest/regtest.cmd" 7
"/home/moebius/reactos/boot/bootdata/readme.txt" 1
"$<TARGET_FILE:atactl>" 2
"$<TARGET_FILE:cacls>" 2
"$<TARGET_FILE:calc>" 2
"$<TARGET_FILE:charmap>" 2
"$<TARGET_FILE:cleanmgr>" 2
"$<TARGET_FILE:clipbrd>" 2
"$<TARGET_FILE:at>" 2
"$<TARGET_FILE:attrib>" 2
"$<TARGET_FILE:certutil>" 2
"$<TARGET_FILE:chcp>" 2
"$<TARGET_FILE:clip>" 2
"$<TARGET_FILE:comp>" 2
"$<TARGET_FILE:cscript>" 2
"$<TARGET_FILE:dbgprint>" 2
"$<TARGET_FILE:doskey>" 2
"$<TARGET_FILE:eventcreate>" 2
"$<TARGET_FILE:fc>" 2
"$<TARGET_FILE:find>" 2
"$<TARGET_FILE:fsutil>" 2
"$<TARGET_FILE:cmd_help>" 2
"$<TARGET_FILE:hostname>" 2
"$<TARGET_FILE:label>" 2
"$<TARGET_FILE:lodctr>" 2
"$<TARGET_FILE:mode>" 2
"$<TARGET_FILE:mofcomp>" 17
"$<TARGET_FILE:more>" 2
"$<TARGET_FILE:reg>" 2
"$<TARGET_FILE:replace>" 2
"$<TARGET_FILE:schtasks>" 2
"$<TARGET_FILE:sort>" 2
"$<TARGET_FILE:taskkill>" 2
"$<TARGET_FILE:tasklist>" 2
"$<TARGET_FILE:timeout>" 2
"$<TARGET_FILE:tree>" 2
"$<TARGET_FILE:where>" 2
"$<TARGET_FILE:whoami>" 2
"$<TARGET_FILE:wmic>" 17
"$<TARGET_FILE:wscript>" 2
"$<TARGET_FILE:xcopy>" 2
"$<TARGET_FILE:control>" 2
"$<TARGET_FILE:drwtsn32>" 2
"$<TARGET_FILE:dxdiag>" 2
"$<TARGET_FILE:extrac32>" 2
"$<TARGET_FILE:findstr>" 2
"$<TARGET_FILE:fltmc>" 2
"$<TARGET_FILE:fontview>" 2
"$<TARGET_FILE:sol>" 2
"$<TARGET_FILE:spider>" 2
"$<TARGET_FILE:winmine>" 2
"$<TARGET_FILE:hh>" 1
"$<TARGET_FILE:iexplore>" 1
"$<TARGET_FILE:kbswitch>" 2
"$<TARGET_FILE:indicdll>" 2
"$<TARGET_FILE:logoff>" 2
"$<TARGET_FILE:magnify>" 2
"$<TARGET_FILE:mmc>" 2
"$<TARGET_FILE:mplay32>" 2
"$<TARGET_FILE:msconfig>" 2
"$<TARGET_FILE:devmgmt>" 2
"$<TARGET_FILE:eventvwr>" 2
"$<TARGET_FILE:servman>" 2
"$<TARGET_FILE:mshta>" 2
"$<TARGET_FILE:mspaint>" 2
"$<TARGET_FILE:mstsc>" 2
"$<TARGET_FILE:arp>" 2
"$<TARGET_FILE:dwnl>" 2
"$<TARGET_FILE:finger>" 2
"$<TARGET_FILE:ftp>" 2
"$<TARGET_FILE:ipconfig>" 2
"$<TARGET_FILE:net>" 2
"$<TARGET_FILE:netsh>" 2
"$<TARGET_FILE:netstat>" 2
"$<TARGET_FILE:nslookup>" 2
"$<TARGET_FILE:ping>" 2
"$<TARGET_FILE:route>" 2
"$<TARGET_FILE:telnet>" 2
"$<TARGET_FILE:tracert>" 2
"$<TARGET_FILE:whois>" 2
"$<TARGET_FILE:wlanconf>" 2
"$<TARGET_FILE:notepad>" 1
"$<TARGET_FILE:notepad>" 2
"$<TARGET_FILE:osk>" 2
"$<TARGET_FILE:rapps>" 2
"$<TARGET_FILE:rapps.com>" 2
"$<TARGET_FILE:regedit>" 1
"$<TARGET_FILE:clb>" 2
"$<TARGET_FILE:regedt32>" 2
"$<TARGET_FILE:runas>" 2
"$<TARGET_FILE:sc>" 2
"$<TARGET_FILE:3dtext>" 2
"$<TARGET_FILE:logon>" 2
"$<TARGET_FILE:sdbinst>" 2
"$<TARGET_FILE:setup16>" 2
"$<TARGET_FILE:shutdown>" 2
"$<TARGET_FILE:sndrec32>" 2
"$<TARGET_FILE:sndvol32>" 2
"$<TARGET_FILE:taskmgr>" 2
"$<TARGET_FILE:utilman>" 2
"$<TARGET_FILE:umandlg>" 2
"$<TARGET_FILE:winhlp32>" 1
"$<TARGET_FILE:winver>" 2
"$<TARGET_FILE:wordpad>" 2
"$<TARGET_FILE:write>" 2
"$<TARGET_FILE:wusa>" 2
"$<TARGET_FILE:ctfmon>" 2
"$<TARGET_FILE:msctf>" 2
"$<TARGET_FILE:msctfime>" 2
"$<TARGET_FILE:msutb>" 2
"$<TARGET_FILE:audiosrv>" 2
"$<TARGET_FILE:browser>" 2
"$<TARGET_FILE:dcomlaunch>" 2
"$<TARGET_FILE:dhcpcsvc>" 2
"$<TARGET_FILE:dnsrslvr>" 2
"$<TARGET_FILE:eventlog>" 2
"$<TARGET_FILE:netlogon>" 2
"$<TARGET_FILE:nfsd>" 2
"/home/moebius/reactos/base/services/nfsd/netconfig" 5
"/home/moebius/reactos/base/services/nfsd/ms-nfs41-idmap.conf" 5
"$<TARGET_FILE:rpcss>" 2
"$<TARGET_FILE:schedsvc>" 2
"$<TARGET_FILE:seclogon>" 2
"$<TARGET_FILE:shsvcs>" 2
"$<TARGET_FILE:srvsvc>" 2
"$<TARGET_FILE:svchost>" 2
"$<TARGET_FILE:tcpsvcs>" 2
"/home/moebius/reactos/base/services/tcpsvcs/quotes" 5
"$<TARGET_FILE:telnetd>" 2
"$<TARGET_FILE:tftpd>" 2
"$<TARGET_FILE:umpnpmgr>" 2
"$<TARGET_FILE:w32time>" 2
"$<TARGET_FILE:wkssvc>" 2
"$<TARGET_FILE:wlansvc>" 2
"$<TARGET_FILE:wmisvc>" 17
"$<TARGET_FILE:wuauserv>" 2
"$<TARGET_FILE:setup>" 2
"$<TARGET_FILE:cmd>" 2
"$<TARGET_FILE:explorer>" 1
"$<TARGET_FILE:filebrowser>" 1
"$<TARGET_FILE:progman>" 2
"$<TARGET_FILE:autochk>" 2
"$<TARGET_FILE:bootok>" 2
"$<TARGET_FILE:chkdsk>" 2
"$<TARGET_FILE:diskpart>" 2
"$<TARGET_FILE:dllhost>" 2
"$<TARGET_FILE:expand>" 2
"$<TARGET_FILE:format>" 2
"$<TARGET_FILE:logonui>" 2
"$<TARGET_FILE:lsass>" 2
"$<TARGET_FILE:msiexec>" 2
"$<TARGET_FILE:regsvr32>" 2
"$<TARGET_FILE:rundll32>" 2
"$<TARGET_FILE:runonce>" 2
"$<TARGET_FILE:services>" 2
"$<TARGET_FILE:smss>" 2
"$<TARGET_FILE:subst>" 2
"$<TARGET_FILE:userinit>" 2
"$<TARGET_FILE:winlogon>" 2
"$<TARGET_FILE:dxtn>" 2
"$<TARGET_FILE:libjpeg>" 2
"$<TARGET_FILE:libpng>" 2
"$<TARGET_FILE:libtiff>" 2
"$<TARGET_FILE:libtirpc>" 2
"$<TARGET_FILE:libxslt>" 2
"$<TARGET_FILE:mbedtls>" 2
"$<TARGET_FILE:apphelp>" 2
"$<TARGET_FILE:acgenral>" 53
"$<TARGET_FILE:aclayers>" 53
"$<TARGET_FILE:access>" 2
"$<TARGET_FILE:appwiz>" 2
"$<TARGET_FILE:console>" 2
"$<TARGET_FILE:desk>" 2
"$<TARGET_FILE:hdwwiz>" 2
"$<TARGET_FILE:hotplug>" 2
"$<TARGET_FILE:inetcpl>" 2
"$<TARGET_FILE:input>" 2
"$<TARGET_FILE:intl>" 2
"$<TARGET_FILE:joy>" 2
"$<TARGET_FILE:main>" 2
"$<TARGET_FILE:mmsys>" 2
"$<TARGET_FILE:ncpa>" 2
"$<TARGET_FILE:odbccp32i>" 2
"$<TARGET_FILE:openglcfg>" 2
"$<TARGET_FILE:powercfg>" 2
"$<TARGET_FILE:sysdm>" 2
"$<TARGET_FILE:telephon>" 2
"$<TARGET_FILE:timedate>" 2
"$<TARGET_FILE:usrmgr>" 2
"$<TARGET_FILE:wined3dcfg>" 2
"$<TARGET_FILE:d3d8thk>" 2
"$<TARGET_FILE:ksuser>" 2
"$<TARGET_FILE:amstream>" 2
"$<TARGET_FILE:d3d8>" 2
"$<TARGET_FILE:d3d9>" 2
"$<TARGET_FILE:d3dcompiler_43>" 2
"$<TARGET_FILE:d3drm>" 2
"$<TARGET_FILE:d3dx9_24>" 2
"$<TARGET_FILE:d3dx9_25>" 2
"$<TARGET_FILE:d3dx9_26>" 2
"$<TARGET_FILE:d3dx9_27>" 2
"$<TARGET_FILE:d3dx9_28>" 2
"$<TARGET_FILE:d3dx9_29>" 2
"$<TARGET_FILE:d3dx9_30>" 2
"$<TARGET_FILE:d3dx9_31>" 2
"$<TARGET_FILE:d3dx9_32>" 2
"$<TARGET_FILE:d3dx9_33>" 2
"$<TARGET_FILE:d3dx9_34>" 2
"$<TARGET_FILE:d3dx9_35>" 2
"$<TARGET_FILE:d3dx9_36>" 2
"$<TARGET_FILE:d3dx9_37>" 2
"$<TARGET_FILE:d3dx9_38>" 2
"$<TARGET_FILE:d3dx9_39>" 2
"$<TARGET_FILE:d3dx9_40>" 2
"$<TARGET_FILE:d3dx9_41>" 2
"$<TARGET_FILE:d3dx9_42>" 2
"$<TARGET_FILE:d3dx9_43>" 2
"$<TARGET_FILE:d3dxof>" 2
"$<TARGET_FILE:ddraw>" 2
"$<TARGET_FILE:devenum>" 2
"$<TARGET_FILE:dinput>" 2
"$<TARGET_FILE:dinput8>" 2
"$<TARGET_FILE:dmusic>" 2
"$<TARGET_FILE:dplay>" 2
"$<TARGET_FILE:dplayx>" 2
"$<TARGET_FILE:dpnhpast>" 2
"$<TARGET_FILE:dsound>" 2
"$<TARGET_FILE:dxdiagn>" 2
"$<TARGET_FILE:msdmo>" 2
"$<TARGET_FILE:qcap>" 2
"$<TARGET_FILE:qedit>" 2
"$<TARGET_FILE:quartz>" 2
"$<TARGET_FILE:d3dwine>" 2
"$<TARGET_FILE:kbda1>" 2
"$<TARGET_FILE:kbda2>" 2
"$<TARGET_FILE:kbda3>" 2
"$<TARGET_FILE:kbdal>" 2
"$<TARGET_FILE:kbdarme>" 2
"$<TARGET_FILE:kbdarmw>" 2
"$<TARGET_FILE:kbdaze>" 2
"$<TARGET_FILE:kbdazel>" 2
"$<TARGET_FILE:kbdbe>" 2
"$<TARGET_FILE:kbdbga>" 2
"$<TARGET_FILE:kbdbgt>" 2
"$<TARGET_FILE:kbdblr>" 2
"$<TARGET_FILE:kbdbr>" 2
"$<TARGET_FILE:kbdbu>" 2
"$<TARGET_FILE:kbdbur>" 2
"$<TARGET_FILE:kbdcan>" 2
"$<TARGET_FILE:kbdcr>" 2
"$<TARGET_FILE:kbdcz>" 2
"$<TARGET_FILE:kbdcz1>" 2
"$<TARGET_FILE:kbdda>" 2
"$<TARGET_FILE:kbddv>" 2
"$<TARGET_FILE:kbdeo>" 2
"$<TARGET_FILE:kbdest>" 2
"$<TARGET_FILE:kbdfc>" 2
"$<TARGET_FILE:kbdfi>" 2
"$<TARGET_FILE:kbdfr>" 2
"$<TARGET_FILE:kbdgeo>" 2
"$<TARGET_FILE:kbdgerg>" 2
"$<TARGET_FILE:kbdgneo>" 2
"$<TARGET_FILE:kbdgr>" 2
"$<TARGET_FILE:kbdgr1>" 2
"$<TARGET_FILE:kbdgrist>" 2
"$<TARGET_FILE:kbdhe>" 2
"$<TARGET_FILE:kbdheb>" 2
"$<TARGET_FILE:kbdhu>" 2
"$<TARGET_FILE:kbdic>" 2
"$<TARGET_FILE:kbdinasa>" 2
"$<TARGET_FILE:kbdinben>" 2
"$<TARGET_FILE:kbdindev>" 2
"$<TARGET_FILE:kbdinguj>" 2
"$<TARGET_FILE:kbdinmal>" 2
"$<TARGET_FILE:kbdir>" 2
"$<TARGET_FILE:kbdit>" 2
"$<TARGET_FILE:kbdjpn>" 2
"$<TARGET_FILE:kbdkaz>" 2
"$<TARGET_FILE:kbdkor>" 2
"$<TARGET_FILE:kbdla>" 2
"$<TARGET_FILE:kbdlt1>" 2
"$<TARGET_FILE:kbdlv>" 2
"$<TARGET_FILE:kbdmac>" 2
"$<TARGET_FILE:kbdne>" 2
"$<TARGET_FILE:kbdno>" 2
"$<TARGET_FILE:kbdpl>" 2
"$<TARGET_FILE:kbdpl1>" 2
"$<TARGET_FILE:kbdpo>" 2
"$<TARGET_FILE:kbdro>" 2
"$<TARGET_FILE:kbdrost>" 2
"$<TARGET_FILE:kbdru>" 2
"$<TARGET_FILE:kbdru1>" 2
"$<TARGET_FILE:kbdsf>" 2
"$<TARGET_FILE:kbdsg>" 2
"$<TARGET_FILE:kbdsl>" 2
"$<TARGET_FILE:kbdsl1>" 2
"$<TARGET_FILE:kbdsp>" 2
"$<TARGET_FILE:kbdsw>" 2
"$<TARGET_FILE:kbdtat>" 2
"$<TARGET_FILE:kbdth0>" 2
"$<TARGET_FILE:kbdth1>" 2
"$<TARGET_FILE:kbdth2>" 2
"$<TARGET_FILE:kbdth3>" 2
"$<TARGET_FILE:kbdtuf>" 2
"$<TARGET_FILE:kbdtuq>" 2
"$<TARGET_FILE:kbduk>" 2
"$<TARGET_FILE:kbdur>" 2
"$<TARGET_FILE:kbdurs>" 2
"$<TARGET_FILE:kbdus>" 2
"$<TARGET_FILE:kbdusa>" 2
"$<TARGET_FILE:kbdusl>" 2
"$<TARGET_FILE:kbdusr>" 2
"$<TARGET_FILE:kbdusx>" 2
"$<TARGET_FILE:kbduzb>" 2
"$<TARGET_FILE:kbdvntc>" 2
"$<TARGET_FILE:kbdycc>" 2
"$<TARGET_FILE:kbdycl>" 2
"$<TARGET_FILE:normaliz>" 2
"$<TARGET_FILE:nfs41_np>" 2
"$<TARGET_FILE:ntdll_vista>" 2
"$<TARGET_FILE:glu32>" 2
"$<TARGET_FILE:opengl32>" 2
"$<TARGET_FILE:acppage>" 2
"$<TARGET_FILE:cabview>" 2
"$<TARGET_FILE:cryptext>" 2
"$<TARGET_FILE:deskadp>" 2
"$<TARGET_FILE:deskmon>" 2
"$<TARGET_FILE:devcpux>" 2
"$<TARGET_FILE:fontext>" 2
"$<TARGET_FILE:mydocs>" 2
"$<TARGET_FILE:netplwiz>" 2
"$<TARGET_FILE:netshell>" 2
"$<TARGET_FILE:ntobjshex>" 2
"$<TARGET_FILE:sendmail>" 2
"$<TARGET_FILE:shellbtrfs>" 2
"$<TARGET_FILE:stobject>" 2
"$<TARGET_FILE:zipfldr>" 2
"$<TARGET_FILE:acledit>" 2
"$<TARGET_FILE:aclui>" 2
"$<TARGET_FILE:activeds>" 2
"$<TARGET_FILE:actxprxy>" 2
"$<TARGET_FILE:advapi32>" 2
"$<TARGET_FILE:advapi32_vista>" 2
"$<TARGET_FILE:advpack>" 2
"$<TARGET_FILE:atl>" 2
"$<TARGET_FILE:atl100>" 2
"$<TARGET_FILE:atl80>" 2
"$<TARGET_FILE:authz>" 2
"$<TARGET_FILE:avicap32>" 2
"$<TARGET_FILE:avifil32>" 2
"$<TARGET_FILE:batt>" 2
"$<TARGET_FILE:bcrypt>" 2
"$<TARGET_FILE:beepmidi>" 2
"$<TARGET_FILE:browseui>" 2
"$<TARGET_FILE:bthci>" 2
"$<TARGET_FILE:cabinet>" 2
"$<TARGET_FILE:cards>" 2
"$<TARGET_FILE:cfgmgr32>" 2
"$<TARGET_FILE:clusapi>" 2
"$<TARGET_FILE:comcat>" 2
"$<TARGET_FILE:comctl32>" 2
"$<TARGET_FILE:comctl32>" 67
"$<TARGET_FILE:comctl32>" 68
"/home/moebius/reactos/dll/win32/comctl32/amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.2600.2982_none_deadbeef.manifest" 55
"/home/moebius/reactos/dll/win32/comctl32/amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.2600.2982_none_deadbeef.manifest" 55
"$<TARGET_FILE:comdlg32>" 2
"$<TARGET_FILE:compstui>" 2
"$<TARGET_FILE:credui>" 2
"$<TARGET_FILE:crypt32>" 2
"$<TARGET_FILE:cryptdlg>" 2
"$<TARGET_FILE:cryptdll>" 2
"$<TARGET_FILE:cryptnet>" 2
"$<TARGET_FILE:cryptui>" 2
"$<TARGET_FILE:dbgeng>" 2
"$<TARGET_FILE:dbghelp>" 2
"$<TARGET_FILE:dciman32>" 2
"$<TARGET_FILE:devmgr>" 2
"$<TARGET_FILE:dnsapi>" 2
"$<TARGET_FILE:esent>" 2
"$<TARGET_FILE:faultrep>" 2
"$<TARGET_FILE:fltlib>" 2
"$<TARGET_FILE:fmifs>" 2
"$<TARGET_FILE:fontsub>" 2
"$<TARGET_FILE:framedyn>" 17
"$<TARGET_FILE:fusion>" 12
"$<TARGET_FILE:fusion>" 2
"$<TARGET_FILE:fusion_1_1>" 13
"$<TARGET_FILE:fusion_2_0>" 14
"$<TARGET_FILE:gdiplus>" 2
"$<TARGET_FILE:gdiplus>" 69
"/home/moebius/reactos/dll/win32/gdiplus/amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.7601.23038_none_deadbeef.manifest" 55
"$<TARGET_FILE:gdiplus>" 71
"/home/moebius/reactos/dll/win32/gdiplus/amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.0.14393.0_none_deadbeef.manifest" 55
"$<TARGET_FILE:getuname>" 2
"$<TARGET_FILE:hhctrl>" 2
"$<TARGET_FILE:hid>" 2
"$<TARGET_FILE:hlink>" 2
"$<TARGET_FILE:hnetcfg>" 2
"$<TARGET_FILE:httpapi>" 2
"$<TARGET_FILE:iccvid>" 2
"$<TARGET_FILE:icmp>" 2
"$<TARGET_FILE:ieframe>" 2
"$<TARGET_FILE:iernonce>" 2
"$<TARGET_FILE:imaadp32.acm>" 2
"$<TARGET_FILE:imagehlp>" 2
"$<TARGET_FILE:inetcomm>" 2
"$<TARGET_FILE:inetmib1>" 2
"$<TARGET_FILE:initpki>" 2
"$<TARGET_FILE:inseng>" 2
"$<TARGET_FILE:iologmsg>" 2
"$<TARGET_FILE:iphlpapi>" 2
"$<TARGET_FILE:itircl>" 2
"$<TARGET_FILE:itss>" 2
"$<TARGET_FILE:jscript>" 2
"$<TARGET_FILE:jsproxy>" 2
"$<TARGET_FILE:kernel32_vista>" 2
"$<TARGET_FILE:kernel32>" 2
"$<TARGET_FILE:loadperf>" 2
"$<TARGET_FILE:lpk>" 2
"$<TARGET_FILE:lsasrv>" 2
"$<TARGET_FILE:lz32>" 2
"$<TARGET_FILE:mapi32>" 2
"$<TARGET_FILE:mciavi32>" 2
"$<TARGET_FILE:mcicda>" 2
"$<TARGET_FILE:mciqtz32>" 2
"$<TARGET_FILE:mciseq>" 2
"$<TARGET_FILE:mciwave>" 2
"$<TARGET_FILE:mgmtapi>" 2
"$<TARGET_FILE:mlang>" 2
"$<TARGET_FILE:mmdrv>" 2
"$<TARGET_FILE:modemui>" 2
"$<TARGET_FILE:mpr>" 2
"$<TARGET_FILE:mprapi>" 2
"$<TARGET_FILE:msacm32>" 2
"$<TARGET_FILE:msacm32.drv>" 2
"$<TARGET_FILE:msadp32.acm>" 2
"$<TARGET_FILE:msafd>" 2
"$<TARGET_FILE:mscat32>" 2
"$<TARGET_FILE:mscms>" 2
"$<TARGET_FILE:mscoree>" 2
"$<TARGET_FILE:msftedit>" 2
"$<TARGET_FILE:msg711.acm>" 2
"$<TARGET_FILE:msgina>" 2
"$<TARGET_FILE:msgsm32.acm>" 2
"$<TARGET_FILE:mshtml>" 2
"$<TARGET_FILE:msi>" 2
"$<TARGET_FILE:mshtml.tlb>" 2
"$<TARGET_FILE:msimg32>" 2
"$<TARGET_FILE:msimtf>" 2
"$<TARGET_FILE:msisip>" 2
"$<TARGET_FILE:msisys>" 2
"$<TARGET_FILE:mspatcha>" 2
"$<TARGET_FILE:msports>" 2
"$<TARGET_FILE:msrle32>" 2
"$<TARGET_FILE:mssign32>" 2
"$<TARGET_FILE:mssip32>" 2
"$<TARGET_FILE:mstask>" 2
"$<TARGET_FILE:msv1_0>" 2
"$<TARGET_FILE:msvcrt>" 2
"$<TARGET_FILE:msvfw32>" 2
"$<TARGET_FILE:msvidc32>" 2
"$<TARGET_FILE:mswsock>" 2
"$<TARGET_FILE:msxml>" 2
"$<TARGET_FILE:msxml2>" 2
"$<TARGET_FILE:msxml3>" 2
"$<TARGET_FILE:msxml3r>" 2
"$<TARGET_FILE:msxml4>" 2
"$<TARGET_FILE:msxml6>" 2
"$<TARGET_FILE:mycomput>" 2
"$<TARGET_FILE:nddeapi>" 2
"$<TARGET_FILE:netapi32>" 2
"$<TARGET_FILE:netcfgx>" 2
"$<TARGET_FILE:netevent>" 2
"$<TARGET_FILE:netid>" 2
"$<TARGET_FILE:netmsg>" 2
"$<TARGET_FILE:newdev>" 2
"$<TARGET_FILE:npptools>" 2
"$<TARGET_FILE:ntdsapi>" 2
"$<TARGET_FILE:ntlanman>" 2
"$<TARGET_FILE:ntmarta>" 2
"$<TARGET_FILE:objsel>" 2
"$<TARGET_FILE:odbc32>" 2
"$<TARGET_FILE:odbccp32>" 2
"$<TARGET_FILE:ole32>" 2
"$<TARGET_FILE:oleacc>" 2
"$<TARGET_FILE:oleaut32>" 2
"$<TARGET_FILE:olecli32>" 2
"$<TARGET_FILE:oledlg>" 2
"$<TARGET_FILE:olepro32>" 2
"$<TARGET_FILE:olesvr32>" 2
"$<TARGET_FILE:olethk32>" 2
"$<TARGET_FILE:pdh>" 2
"$<TARGET_FILE:pidgen>" 2
"$<TARGET_FILE:powrprof>" 2
"$<TARGET_FILE:profmap>" 2
"$<TARGET_FILE:propsys>" 2
"$<TARGET_FILE:psapi>" 2
"$<TARGET_FILE:pstorec>" 2
"$<TARGET_FILE:qmgr>" 2
"$<TARGET_FILE:qmgrprxy>" 2
"$<TARGET_FILE:query>" 2
"$<TARGET_FILE:rasadhlp>" 2
"$<TARGET_FILE:rasapi32>" 2
"$<TARGET_FILE:rasdlg>" 2
"$<TARGET_FILE:rasman>" 2
"$<TARGET_FILE:regapi>" 2
"$<TARGET_FILE:resutils>" 2
"$<TARGET_FILE:riched20>" 2
"$<TARGET_FILE:riched32>" 2
"$<TARGET_FILE:rpcrt4>" 2
"$<TARGET_FILE:rsabase>" 2
"$<TARGET_FILE:rsaenh>" 2
"$<TARGET_FILE:samlib>" 2
"$<TARGET_FILE:samsrv>" 2
"$<TARGET_FILE:sccbase>" 2
"$<TARGET_FILE:schannel>" 2
"$<TARGET_FILE:scrrun>" 2
"$<TARGET_FILE:secur32>" 2
"$<TARGET_FILE:security>" 2
"$<TARGET_FILE:sensapi>" 2
"$<TARGET_FILE:serialui>" 2
"$<TARGET_FILE:setupapi>" 2
"$<TARGET_FILE:sfc>" 2
"$<TARGET_FILE:sfc_os>" 2
"$<TARGET_FILE:sfcfiles>" 2
"$<TARGET_FILE:shdoclc>" 2
"$<TARGET_FILE:shdocvw>" 2
"$<TARGET_FILE:shell32>" 2
"$<TARGET_FILE:shfolder>" 2
"$<TARGET_FILE:shimgvw>" 2
"$<TARGET_FILE:shlwapi>" 2
"$<TARGET_FILE:slbcsp>" 2
"$<TARGET_FILE:sndblst>" 2
"$<TARGET_FILE:snmpapi>" 2
"$<TARGET_FILE:softpub>" 2
"$<TARGET_FILE:srclient>" 2
"$<TARGET_FILE:stdole2.tlb>" 2
"$<TARGET_FILE:stdole32.tlb>" 2
"$<TARGET_FILE:sti>" 2
"$<TARGET_FILE:storprop>" 2
"$<TARGET_FILE:streamci>" 2
"$<TARGET_FILE:sxs>" 2
"$<TARGET_FILE:syssetup>" 2
"$<TARGET_FILE:t2embed>" 2
"$<TARGET_FILE:tapi32>" 2
"$<TARGET_FILE:tapiui>" 2
"$<TARGET_FILE:themeui>" 2
"$<TARGET_FILE:traffic>" 2
"$<TARGET_FILE:twain_32>" 1
"$<TARGET_FILE:ubtrfs>" 2
"$<TARGET_FILE:ucdfs>" 2
"$<TARGET_FILE:ucrtbase>" 2
"$<TARGET_FILE:uext2>" 2
"$<TARGET_FILE:ufat>" 2
"$<TARGET_FILE:ufatx>" 2
"$<TARGET_FILE:untfs>" 2
"$<TARGET_FILE:updspapi>" 2
"$<TARGET_FILE:url>" 2
"$<TARGET_FILE:urlmon>" 2
"$<TARGET_FILE:userenv>" 2
"$<TARGET_FILE:usp10>" 2
"$<TARGET_FILE:uxtheme>" 2
"$<TARGET_FILE:vbscript>" 2
"$<TARGET_FILE:verifier>" 2
"$<TARGET_FILE:version>" 2
"$<TARGET_FILE:vssapi>" 2
"$<TARGET_FILE:wbemdisp>" 17
"$<TARGET_FILE:wbemprox>" 17
"$<TARGET_FILE:wdmaud.drv>" 2
"$<TARGET_FILE:windowscodecs>" 2
"$<TARGET_FILE:windowscodecsext>" 2
"$<TARGET_FILE:winemp3.acm>" 2
"$<TARGET_FILE:winfax>" 2
"$<TARGET_FILE:wing32>" 2
"$<TARGET_FILE:winhttp>" 2
"$<TARGET_FILE:wininet>" 2
"$<TARGET_FILE:winmm>" 2
"$<TARGET_FILE:midimap>" 2
"$<TARGET_FILE:winscard>" 2
"$<TARGET_FILE:winsta>" 2
"$<TARGET_FILE:wintrust>" 2
"$<TARGET_FILE:wlanapi>" 2
"$<TARGET_FILE:wldap32>" 2
"$<TARGET_FILE:wlnotify>" 2
"$<TARGET_FILE:wmi>" 2
"$<TARGET_FILE:wmiutils>" 17
"$<TARGET_FILE:wmvcore>" 2
"$<TARGET_FILE:ws2_32>" 2
"$<TARGET_FILE:ws2help>" 2
"$<TARGET_FILE:wshirda>" 2
"$<TARGET_FILE:wshom>" 2
"$<TARGET_FILE:wshtcpip>" 2
"$<TARGET_FILE:wsock32>" 2
"$<TARGET_FILE:wtsapi32>" 2
"$<TARGET_FILE:wuapi>" 2
"$<TARGET_FILE:xinput1_1>" 2
"$<TARGET_FILE:xinput1_2>" 2
"$<TARGET_FILE:xinput1_3>" 2
"$<TARGET_FILE:xinput9_1_0>" 2
"$<TARGET_FILE:xmllite>" 2
"$<TARGET_FILE:xolehlp>" 2
"$<TARGET_FILE:cmbatt>" 3
"$<TARGET_FILE:beep>" 3
"$<TARGET_FILE:null>" 3
"$<TARGET_FILE:battc>" 3
"$<TARGET_FILE:compbatt>" 3
"$<TARGET_FILE:fbtusb>" 3
"/home/moebius/reactos/output-posix-amd64/drivers/bus/acpi/acpi.inf" 6
"/home/moebius/reactos/output-posix-amd64/drivers/filesystems/btrfs/btrfs.inf" 6
"$<TARGET_FILE:ext2fs>" 3
"$<TARGET_FILE:fs_rec>" 3
"$<TARGET_FILE:msfs>" 3
"$<TARGET_FILE:mup>" 3
"$<TARGET_FILE:nfs41_driver>" 3
"$<TARGET_FILE:npfs>" 3
"$<TARGET_FILE:ntfs>" 3
"$<TARGET_FILE:udfs>" 3
"$<TARGET_FILE:mouhid>" 3
"$<TARGET_FILE:inport>" 3
"$<TARGET_FILE:mouclass>" 3
"$<TARGET_FILE:sermouse>" 3
"$<TARGET_FILE:ks>" 3
"$<TARGET_FILE:bdasup>" 3
"$<TARGET_FILE:afd>" 3
"$<TARGET_FILE:dc21x4>" 3
"/home/moebius/reactos/output-posix-amd64/drivers/network/dd/dc21x4/net21x4.inf" 6
"$<TARGET_FILE:e1000>" 3
"/home/moebius/reactos/output-posix-amd64/drivers/network/dd/e1000/nete1000.inf" 6
"$<TARGET_FILE:ne2000>" 3
"/home/moebius/reactos/output-posix-amd64/drivers/network/dd/ne2000/netne.inf" 6
"$<TARGET_FILE:netkvm>" 3
"/home/moebius/reactos/output-posix-amd64/drivers/network/dd/netkvm/netkvm.inf" 6
"$<TARGET_FILE:nvnet>" 3
"/home/moebius/reactos/output-posix-amd64/drivers/network/dd/nvnet/netnv.inf" 6
"$<TARGET_FILE:pcnet>" 3
"/home/moebius/reactos/output-posix-amd64/drivers/network/dd/pcnet/netamd.inf" 6
"$<TARGET_FILE:rtl8139>" 3
"/home/moebius/reactos/output-posix-amd64/drivers/network/dd/rtl8139/netrtl.inf" 6
"$<TARGET_FILE:ndis>" 3
"$<TARGET_FILE:ndisuio>" 3
"$<TARGET_FILE:tcpip>" 3
"$<TARGET_FILE:tdi>" 3
"$<TARGET_FILE:parport>" 3
"$<TARGET_FILE:processr>" 3
"/home/moebius/reactos/output-posix-amd64/drivers/processor/processr/cpu.inf" 6
"$<TARGET_FILE:serenum>" 3
"$<TARGET_FILE:serial>" 3
"/home/moebius/reactos/output-posix-amd64/drivers/storage/class/cdrom/cdrom.inf" 6
"/home/moebius/reactos/output-posix-amd64/drivers/storage/class/disk/disk.inf" 6
"/home/moebius/reactos/output-posix-amd64/drivers/storage/class/ramdisk/ramdisk.inf" 6
"/home/moebius/reactos/output-posix-amd64/drivers/storage/ide/uniata/uniata_comm.inf" 6
"/home/moebius/reactos/output-posix-amd64/drivers/usb/usbstor/usbstor.inf" 6
"$<TARGET_FILE:portcls>" 3
"$<TARGET_FILE:ac97>" 3
"/home/moebius/reactos/output-posix-amd64/drivers/wdm/audio/drivers/ac97/ac97.inf" 6
"$<TARGET_FILE:cmicontrol>" 3
"$<TARGET_FILE:cmicpl>" 3
"$<TARGET_FILE:cmipci>" 3
"/home/moebius/reactos/drivers/wdm/audio/drivers/CMIDriver/CM8738-x64.inf" 6
"$<TARGET_FILE:drmk>" 3
"$<TARGET_FILE:kmixer>" 3
"$<TARGET_FILE:hdaudbus>" 3
"/home/moebius/reactos/output-posix-amd64/drivers/wdm/audio/hdaudbus/hdaudbus.inf" 6
"$<TARGET_FILE:wdmaud>" 3
"$<TARGET_FILE:sysaudio>" 3
"/home/moebius/reactos/media/fonts/arial.ttf" 4
"/home/moebius/reactos/media/fonts/arialbd.ttf" 4
"/home/moebius/reactos/media/fonts/arialbi.ttf" 4
"/home/moebius/reactos/media/fonts/ariali.ttf" 4
"/home/moebius/reactos/media/fonts/ariblk.ttf" 4
"/home/moebius/reactos/media/fonts/comic.ttf" 4
"/home/moebius/reactos/media/fonts/comicbd.ttf" 4
"/home/moebius/reactos/media/fonts/cour.ttf" 4
"/home/moebius/reactos/media/fonts/courbd.ttf" 4
"/home/moebius/reactos/media/fonts/courbi.ttf" 4
"/home/moebius/reactos/media/fonts/couri.ttf" 4
"/home/moebius/reactos/media/fonts/framd.ttf" 4
"/home/moebius/reactos/media/fonts/framdit.ttf" 4
"/home/moebius/reactos/media/fonts/FreeSans.ttf" 4
"/home/moebius/reactos/media/fonts/FreeSansBold.ttf" 4
"/home/moebius/reactos/media/fonts/FreeSansBoldOblique.ttf" 4
"/home/moebius/reactos/media/fonts/FreeSansOblique.ttf" 4
"/home/moebius/reactos/media/fonts/FSEX301.ttf" 4
"/home/moebius/reactos/media/fonts/FSEX301-L2.ttf" 4
"/home/moebius/reactos/media/fonts/georgia.ttf" 4
"/home/moebius/reactos/media/fonts/georgiab.ttf" 4
"/home/moebius/reactos/media/fonts/georgiai.ttf" 4
"/home/moebius/reactos/media/fonts/georgiaz.ttf" 4
"/home/moebius/reactos/media/fonts/lucon.ttf" 4
"/home/moebius/reactos/media/fonts/Marlett.ttf" 4
"/home/moebius/reactos/media/fonts/micross.ttf" 4
"/home/moebius/reactos/media/fonts/pala.ttf" 4
"/home/moebius/reactos/media/fonts/palab.ttf" 4
"/home/moebius/reactos/media/fonts/palabi.ttf" 4
"/home/moebius/reactos/media/fonts/palai.ttf" 4
"/home/moebius/reactos/media/fonts/SourceSansPro-Regular.ttf" 4
"/home/moebius/reactos/media/fonts/SourceSansPro-Bold.ttf" 4
"/home/moebius/reactos/media/fonts/SourceSansPro-BoldIt.ttf" 4
"/home/moebius/reactos/media/fonts/SourceSansPro-It.ttf" 4
"/home/moebius/reactos/media/fonts/symbol.ttf" 4
"/home/moebius/reactos/media/fonts/tahoma.ttf" 4
"/home/moebius/reactos/media/fonts/tahomabd.ttf" 4
"/home/moebius/reactos/media/fonts/times.ttf" 4
"/home/moebius/reactos/media/fonts/timesbd.ttf" 4
"/home/moebius/reactos/media/fonts/timesbi.ttf" 4
"/home/moebius/reactos/media/fonts/timesi.ttf" 4
"/home/moebius/reactos/media/fonts/trebuc.ttf" 4
"/home/moebius/reactos/media/fonts/trebucbd.ttf" 4
"/home/moebius/reactos/media/fonts/trebucbi.ttf" 4
"/home/moebius/reactos/media/fonts/trebucit.ttf" 4
"/home/moebius/reactos/media/fonts/UniVGA16.ttf" 4
"/home/moebius/reactos/media/fonts/verdanab.ttf" 4
"/home/moebius/reactos/media/fonts/verdanaz.ttf" 4
"/home/moebius/reactos/media/fonts/verdanai.ttf" 4
"/home/moebius/reactos/media/fonts/verdana.ttf" 4
"/home/moebius/reactos/media/fonts/wingding.ttf" 4
"/home/moebius/reactos/output-posix-amd64/media/inf/audio.inf" 6
"/home/moebius/reactos/output-posix-amd64/media/inf/battery.inf" 6
"/home/moebius/reactos/output-posix-amd64/media/inf/bda.inf" 6
"/home/moebius/reactos/output-posix-amd64/media/inf/bth.inf" 6
"/home/moebius/reactos/output-posix-amd64/media/inf/c_image.inf" 6
"/home/moebius/reactos/output-posix-amd64/media/inf/display.inf" 6
"/home/moebius/reactos/output-posix-amd64/media/inf/fdc.inf" 6
"/home/moebius/reactos/output-posix-amd64/media/inf/flpydisk.inf" 6
"/home/moebius/reactos/output-posix-amd64/media/inf/hal.inf" 6
"/home/moebius/reactos/output-posix-amd64/media/inf/hdc.inf" 6
"/home/moebius/reactos/output-posix-amd64/media/inf/input.inf" 6
"/home/moebius/reactos/output-posix-amd64/media/inf/keyboard.inf" 6
"/home/moebius/reactos/output-posix-amd64/media/inf/ks.inf" 6
"/home/moebius/reactos/output-posix-amd64/media/inf/kscaptur.inf" 6
"/home/moebius/reactos/output-posix-amd64/media/inf/legcydrv.inf" 6
"/home/moebius/reactos/output-posix-amd64/media/inf/machine.inf" 6
"/home/moebius/reactos/output-posix-amd64/media/inf/monitor.inf" 6
"/home/moebius/reactos/output-posix-amd64/media/inf/msmouse.inf" 6
"/home/moebius/reactos/output-posix-amd64/media/inf/ndisuio.inf" 6
"/home/moebius/reactos/output-posix-amd64/media/inf/NET_NIC.inf" 6
"/home/moebius/reactos/output-posix-amd64/media/inf/nettcpip.inf" 6
"/home/moebius/reactos/output-posix-amd64/media/inf/ports.inf" 6
"/home/moebius/reactos/output-posix-amd64/media/inf/scsi.inf" 6
"/home/moebius/reactos/output-posix-amd64/media/inf/shortcuts.inf" 6
"/home/moebius/reactos/output-posix-amd64/media/inf/unknown.inf" 6
"/home/moebius/reactos/output-posix-amd64/media/inf/usb.inf" 6
"/home/moebius/reactos/output-posix-amd64/media/inf/usbport.inf" 6
"/home/moebius/reactos/output-posix-amd64/media/inf/volume.inf" 6
"/home/moebius/reactos/output-posix-amd64/media/inf/wdmaudio.inf" 6
"/home/moebius/reactos/output-posix-amd64/media/inf/wmiacpi.inf" 6
"/home/moebius/reactos/media/inf/defltwk.inf" 6
"/home/moebius/reactos/media/inf/font.inf" 6
"/home/moebius/reactos/media/inf/intl.inf" 6
"/home/moebius/reactos/media/inf/layout.inf" 6
"/home/moebius/reactos/media/inf/syssetup.inf" 6
"/home/moebius/reactos/output-posix-amd64/media/nls/c_037.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_10000.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_10001.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_10002.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_10003.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_10004.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_10005.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_10006.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_10007.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_10008.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_10010.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_10017.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_10021.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_10029.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_10079.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_10081.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_10082.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_1006.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_1026.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_1047.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_1140.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_1141.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_1142.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_1143.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_1144.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_1145.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_1146.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_1147.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_1148.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_1149.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_1250.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_1251.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_1253.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_1254.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_1255.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_1256.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_1257.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_1258.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_1361.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_20000.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_20001.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_20002.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_20003.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_20004.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_20005.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_20105.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_20106.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_20107.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_20108.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_20127.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_20261.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_20269.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_20273.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_20277.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_20278.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_20280.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_20284.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_20285.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_20290.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_20297.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_20420.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_20423.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_20424.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_20833.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_20838.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_20866.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_20871.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_20880.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_20905.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_20924.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_21025.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_21027.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_21866.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_28591.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_28592.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_28593.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_28594.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_28595.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_28596.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_28597.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_28598.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_28599.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_28600.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_28603.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_28604.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_28605.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_28606.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_29001.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_424.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_500.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_708.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_720.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_737.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_775.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_850.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_852.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_855.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_857.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_858.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_860.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_861.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_862.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_863.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_864.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_865.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_866.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_869.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_870.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_874.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_875.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_932.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_936.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_949.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/nls/c_950.nls" 2
"/home/moebius/reactos/media/nls/c_856.nls" 2
"/home/moebius/reactos/media/nls/c_878.nls" 2
"/home/moebius/reactos/media/nls/ctype.nls" 2
"/home/moebius/reactos/media/nls/geo.nls" 2
"/home/moebius/reactos/media/nls/l_except.nls" 2
"/home/moebius/reactos/media/nls/locale.nls" 2
"/home/moebius/reactos/media/nls/sortkey.nls" 2
"/home/moebius/reactos/media/nls/sorttbls.nls" 2
"/home/moebius/reactos/media/nls/unicode.nls" 2
"/home/moebius/reactos/output-posix-amd64/media/sdb/sysmain.sdb" 53
"/home/moebius/reactos/media/sounds/ReactOS_Critical_Stop.wav" 9
"/home/moebius/reactos/media/sounds/ReactOS_Startup.wav" 9
"/home/moebius/reactos/media/sounds/ReactOS_Notify.wav" 9
"/home/moebius/reactos/media/sounds/ReactOS_Recycle.wav" 9
"$<TARGET_FILE:lautus.msstyles>" 18
"$<TARGET_FILE:lunar.msstyles>" 64
"$<TARGET_FILE:mizu.msstyles>" 65
"$<TARGET_FILE:modern.msstyles>" 62
"/home/moebius/reactos/media/drivers/etc/hosts" 5
"/home/moebius/reactos/media/drivers/etc/KDBinit" 5
"/home/moebius/reactos/media/drivers/etc/networks" 5
"/home/moebius/reactos/media/drivers/etc/protocol" 5
"/home/moebius/reactos/media/drivers/etc/services" 5
"/home/moebius/reactos/media/systemcompatible.manifest" 55
"$<TARGET_FILE:csrsrv>" 2
"$<TARGET_FILE:csrss>" 2
"/home/moebius/reactos/subsystems/mvdm/config/AUTOEXEC.NT" 2
"/home/moebius/reactos/subsystems/mvdm/config/AUTOEXEC.NT" 43
"/home/moebius/reactos/subsystems/mvdm/config/CONFIG.NT" 2
"/home/moebius/reactos/subsystems/mvdm/config/CONFIG.NT" 43
"/home/moebius/reactos/subsystems/mvdm/config/system.ini" 1
"/home/moebius/reactos/subsystems/mvdm/config/win.ini" 1
"/home/moebius/reactos/output-posix-amd64/subsystems/mvdm/dos/command.com" 2
"$<TARGET_FILE:ntvdm>" 2
"$<TARGET_FILE:pifmgr>" 2
"$<TARGET_FILE:vdmdbg>" 2
"$<TARGET_FILE:user>" 2
"$<TARGET_FILE:basesrv>" 2
"$<TARGET_FILE:framebuf>" 2
"$<TARGET_FILE:vgaddi>" 2
"$<TARGET_FILE:ftfd>" 2
"$<TARGET_FILE:bochsmp>" 3
"/home/moebius/reactos/output-posix-amd64/win32ss/drivers/miniport/bochs/bochsmp.inf" 6
"$<TARGET_FILE:vgapnp>" 3
"$<TARGET_FILE:vga>" 3
"$<TARGET_FILE:videoprt>" 3
"$<TARGET_FILE:watchdog>" 3
"$<TARGET_FILE:gdi32>" 2
"$<TARGET_FILE:gdi32_vista>" 2
"$<TARGET_FILE:ntprint>" 2
"$<TARGET_FILE:printui>" 2
"$<TARGET_FILE:spoolss>" 2
"$<TARGET_FILE:spoolsv>" 2
"$<TARGET_FILE:winspool>" 2
"$<TARGET_FILE:localui>" 2
"$<TARGET_FILE:localmon>" 2
"$<TARGET_FILE:winprint>" 66
"$<TARGET_FILE:localspl>" 2
"$<TARGET_FILE:dxapi>" 3
"$<TARGET_FILE:dxg>" 3
"$<TARGET_FILE:dxgthk>" 3
"$<TARGET_FILE:imm32>" 2
"$<TARGET_FILE:user32>" 2
"$<TARGET_FILE:user32_vista>" 2
"$<TARGET_FILE:winsrv>" 2
"$<TARGET_FILE:win32k>" 2
