[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
linker = "gcc"
rustflags = [
    "-C", "link-arg=-Tlinker.ld",
    "-C", "link-arg=-nostartfiles",
    "-C", "link-arg=-nodefaultlibs",
    "-C", "link-arg=-Wl,--build-id=none",
    "-C", "link-arg=-Wl,--nmagic",
    "-C", "link-arg=-Wl,--gc-sections",
    "-C", "link-arg=-Wl,-Ttext=0x100000",
    "-C", "link-arg=-Wl,--oformat=binary",
]

[unstable]
build-std = ["core"]
