# Configuración de arquitecturas para ReactOS Rust OS
# Multi-arquitectura por defecto

[architectures]
# Arquitecturas soportadas
x86 = { target = "i686-unknown-none", enabled = true, description = "x86 (32-bit) - Compatibilidad con aplicaciones Windows 32-bit" }
x86_64 = { target = "x86_64-unknown-none", enabled = true, description = "x86_64 (64-bit) - Soporte nativo para aplicaciones Windows 64-bit" }

# Configuración por defecto
default_arch = "x86_64"
multi_arch = true

[build]
# Configuración de build
rust_toolchain = "nightly"
optimization = "release"
lto = true
codegen_units = 1

[iso]
# Configuración de ISO
name = "reactos-rust-os"
hybrid = true
boot_menu = true
timeout = 10

[compatibility]
# Configuración de compatibilidad
wow64 = true
win32_api = true
legacy_drivers = true
