[package]
name = "reactos-windows-unoptimized"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "reactos-windows-unoptimized"
path = "src/main.rs"

[profile.dev]
opt-level = 0
debug = true
overflow-checks = true
